alias aptc='sudo apt-get autoclean; sudo apt-get clean; sudo apt-get autoremove'
alias aptf='aptitude show $1'
alias apts='apt-cache search $1'
alias apti='sudo apt-get install -y $1'
alias aptu='sudo apt-get update; sudo apt-get -y upgrade'
alias aptud='sudo apt-get update; sudo apt-get -y dist-upgrade'
